/*
 * Any strings listed in this file may be refered to with SS(name)
 * for a (string_t *), and SSO(name) for an (object_t *). Maximum
 * 15 chars per string. Users need to include str.h. Wherever possible,
 * the name and the string should be the same.
 *
 * String objects made by this mechanism reside in static initialised
 * memory. They are not allocated or collected, but in other respects
 * are normal.
 *
 * This file is included with variying definitions of SSTRING()
 * from str.h (for global extern defines), and twice from sstring.c.
 */
SSTRING(struct, "struct")
SSTRING(float, "float")
SSTRING(array, "array")
SSTRING(set, "set")
SSTRING(class, "class")
SSTRING(module, "module")
SSTRING(func, "func")
SSTRING(_NULL, "NULL")
SSTRING(in, "in")
SSTRING(onerror, "onerror")
SSTRING(else, "else")
SSTRING(auto, "auto")
SSTRING(break, "break")
SSTRING(case, "case")
SSTRING(continue, "continue")
SSTRING(default, "default")
SSTRING(do, "do")
SSTRING(extern, "extern")
SSTRING(for, "for")
SSTRING(forall, "forall")
SSTRING(if, "if")
SSTRING(return, "return")
SSTRING(static, "static")
SSTRING(switch, "switch")
SSTRING(while, "while")
SSTRING(try, "try")
SSTRING(_funcname_, "_funcname_")
SSTRING(_stdin, "stdin")
SSTRING(_stdout, "stdout")
SSTRING(_stderr, "stderr")
SSTRING(_, "_")
SSTRING(second, "second")
SSTRING(minute, "minute")
SSTRING(hour, "hour")
SSTRING(day, "day")
SSTRING(month, "month")
SSTRING(year, "year")
SSTRING(wday, "wday")
SSTRING(yday, "yday")
SSTRING(isdst, "isdst")
SSTRING(slosh0, "\\0")
SSTRING(sloshn, "\\n")
SSTRING(pattern, "pattern")
SSTRING(options, "options")
SSTRING(empty_string, "")
SSTRING(name, "name")
SSTRING(autos, "autos")
SSTRING(args, "args")
SSTRING(this, "this")
SSTRING(vargs, "vargs")
SSTRING(core, "core")
SSTRING(error, "error")
SSTRING(argc, "argc")
SSTRING(argv, "argv")
SSTRING(subject, "subject")
SSTRING(callable, "callable")
SSTRING(load, "load")
SSTRING(waitfor, "waitfor")
SSTRING(result, "result")
SSTRING(critsect, "critsect")
#ifndef NOCLASSPROTO
SSTRING(proto, "proto")
#endif
